name: Trigger auto deployment for container-app-s6txq34jvxago

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Frontend/**'
    - '.github/workflows/container-app-s6txq34jvxago-AutoDeployTrigger-99991638-9eff-469e-baec-f2f0c956065f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPS6TXQ34JVXAGO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPS6TXQ34JVXAGO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPS6TXQ34JVXAGO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Frontend 
          registryUrl: containerregistrys6txq34jvxago.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPS6TXQ34JVXAGO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPS6TXQ34JVXAGO_REGISTRY_PASSWORD }}
          containerAppName: container-app-s6txq34jvxago
          resourceGroup: sampledotnetworkerswithgrpcmessagingonazurecontainerapps954e
          imageToBuild: containerregistrys6txq34jvxago.azurecr.io/container-app-s6txq34jvxago:${{ github.sha }}
          dockerfilePath: Dockerfile


